### ISSUE TITLE
CRAN has wrong URL for babelmixr2

### ISSUE THREAD

**Issue by bruc** [nlmixr2/babelmixr2#106]
CRAN has the following URL for babelmixr2:

https://cran.r-project.org/web//src/contrib/babelmixr2_0.1.2.tar.gz

It should be 

https://cran.r-project.org/src/contrib/babelmixr2_0.1.2.tar.gz

**Comment by mattfidler** [comment]
When both Uwe and I look the URLs are correct.

Can you provide details on how to reproduce this issue?

Best,

Matt

**Comment by bruc** [comment]
Go to duckduckgo.com and type in

r project babelmixr2

Click on the first link: https://cran.r-project.org/web//packages//babelmixr2/index.html

then, click on the tar-ball link "[babelmixr2_0.1.2.tar.gz"](https://cran.r-project.org/web//src/contrib/babelmixr2_0.1.2.tar.gz)

which is

https://cran.r-project.org/web//src/contrib/babelmixr2_0.1.2.tar.gz

which is not found.

Cheers,
Bob

**Comment by mattfidler** [comment]
This seems like a problem with duck duck go;  I will relay to CRAN but they
do not see a problem right now.

**Comment by bruc** [comment]
I just tried the same search (r project babelmixr2) with Google and I get nearly the same URL except the double slashes change to single slashes (i.e. web//packages//babelmixr2/ from Duck Duck Go is web/packages/babelmixr2 from Google). Please relay this to CRAN -- it's not clear where this problem should be corrected.

Thank you.

**Comment by mattfidler** [comment]
Hi @bruc 

Apparently it has been fixed on duck duck go side.  Now the URL is correct.  I'm unsure what happened.  I just confirmed.

Best,

Matt

**Comment by mattfidler** [comment]
I did relay this to cran too.
