### ISSUE TITLE
poped shrinkage() throws error for all instances tested

### ISSUE THREAD

**Issue by TheoPapath** [nlmixr2/babelmixr2#129]
When trying to compute the shrinkage using shrinkage(), we get the following error:
![image](https://github.com/user-attachments/assets/69ff3d2c-d7d2-4a93-837b-4f55cad086d3)

> traceback()
17: stop(structure(list(message = "Expecting a single value: [extent=0].", 
        call = NULL, cppstack = NULL), class = c("Rcpp::not_compatible", 
    "C++Error", "error", "condition")))
16: babelmixr2::popedMultipleEndpointParam(p, .u, model_switch, 3L, 
        poped.db$babelmixr2$optTime)
15: (function (model_switch, xt, p, poped.db) 
    {
        .xt <- drop(xt)
        .id <- p[1]
        .u <- .xt
        .lu <- length(.u)
        .totn <- length(.xt)
        if (.lu <= 3L) {
            .p <- babelmixr2::popedMultipleEndpointParam(p, .u, model_switch, 
                3L, poped.db$babelmixr2$optTime)
            .popedRxRunSetup(poped.db)
            .ret <- .popedSolveIdME(.p, .u, .xt, model_switch, 1L, 
                .id - 1, .totn)
        }
        else if (.lu > 3L) {
            .p <- p[-1]
            .popedRxRunFullSetupMe(poped.db, .xt, model_switch)
            .ret <- .popedSolveIdME2(.p, .u, .xt, model_switch, 1L, 
                .id - 1, .totn)
        }
     ...
14: do.call(poped.db$model$ff_pointer, list(model_switch, xt, parameters, 
        poped.db))
13: (function (model_switch, xt, parameters, epsi, poped.db) 
    {
        rxReturnArgs <- do.call(poped.db$model$ff_pointer, list(model_switch, 
            xt, parameters, poped.db))
        rxF <- rxReturnArgs[[1]]
        rxPoped.db <- rxReturnArgs[[2]]
        rxErr1 <- rxF * (1 + epsi[, 1]) + epsi[, 2]
        return(list(y = rxErr1, poped.db = rxPoped.db))
    })(structure(c(1, 1, 1), dim = c(3L, 1L), dimnames = list(c("obs_1", 
    "obs_2", "obs_3"), "grp_1")), structure(c(1, 3, 8), dim = c(3L, 
    1L), dimnames = list(c("obs_1", "obs_2", "obs_3"), "grp_1")), 
        c(ID = 1, rx__tKA = 2, rx__tK = 0.25, rx__tV = 15, rx__eta.ka = 1e-05, 
        rx__eta.k = 0, rx__eta.v = 0, DOSE = 100), structure(c(0, 
        0), dim = 1:2), list(settings = list(poped_version = structure(list(
            c(0L, 7L, 0L)), class = c("package_version", "numeric_version"
        )), bLHS = c(hypercube = 1), d_switch = 1, iApproximationMethod = c(fo = 0), 
            iFOCENumInd = 1, bUseRandomSearch = 1, bUseStochasticGradient = 1, 
            bUseLineSearch = 1, bUseExchangeAlgorithm = 0, bUseBFGSMinimizer = 0, 
            iEDCalculationType = c(mc = 0), BFGSConvergenceCriteriaMinStep = 1e-08, 
            BFGSProjectedGradientTol = 1e-04, BFGSTolerancef = 0.001, 
     ...
12: do.call(file.name, list(...))
11: feval(poped.db$model$ferror_pointer, model_switch, xt_ind, g_p, 
        epsi0, poped.db)
10: (function (model_switch, xt_ind, x, a, bpop, b_ind, bocc_ind, 
        d, sigma, docc, poped.db) 
    {
        epsi0 = zeros(1, length(poped.db$parameters$notfixed_sigma))
        if ((poped.db$settings$iApproximationMethod == 0 || poped.db$settings$iApproximationMethod == 
            3)) {
            b_ind = zeros(poped.db$parameters$NumRanEff, 1)
        }
        if ((poped.db$settings$bCalculateEBE)) {
            b_ind = ind_estimates(poped.db$mean_data, bpop, d, sigma, 
                t(b_ind), (poped.db$settings$iApproximationMethod == 
                    2), FALSE, model_switch, xt_ind, x, a, b_ind, 
                bocc_ind, poped.db)
        }
        g_p = feval(poped.db$model$fg_pointer, x, a, bpop, b_ind, 
            bocc_ind)
        returnArgs <- feval(poped.db$model$ferror_pointer, model_switch, 
            xt_ind, g_p, epsi0, poped.db)
        ferror <- returnArgs[[1]]
        if ((poped.db$settings$iApproximationMethod == 0 || poped.db$settings$iApproximationMethod == 
     ...
9: do.call(func, arg_list)
8: grad_all(func, select_par, nout, model_switch, xt_ind, x, a, 
       bpop, b_ind, bocc_ind, d, sigma, docc, poped.db, subset = subset, 
       noPopED = FALSE, offdiag = offdiag)
7: grad_bpop(helper_LinMatrix, 5, size(xt_ind, 1), model_switch, 
       xt_ind, x, a, bpop, b_ind, bocc_ind, d, sigma, docc = NULL, 
       poped.db)
6: m1(model_switch, xt, x, a, bpop, b_ind, bocc_ind, d, sigma, poped.db)
5: mf3(model_switch, xt_ind, x, a, bpop, d, sigma, docc, poped.db)
4: mf_all(t(model_switch[i, 1:ni[i, drop = F], drop = F]), t(xt[i, 
       1:ni[i, drop = F], drop = F]), x_i, a_i, bpop, d, sigma, 
       docc, poped.db)
3: mftot(model_switch, groupsize, ni, xt, x, a, bpop.val, d_full, 
       sigma_full, docc_full, poped.db, ...)
2: evaluate.fim(poped.db_sh)
1: shrinkage(babel.db)

**Comment by mattfidler** [comment]
Please attach the code that produces this in a reproducible example so I can figure this out 😄

**Comment by TheoPapath** [comment]
I created a new branch:
![image](https://github.com/user-attachments/assets/0296acf9-1aa3-4e15-bafb-7a14c8fe66e2)

The code can be found here:
babelmixr2/inst/poped/ex.13.shrinkage.babelmixr2.R

**Comment by mattfidler** [comment]
``` gdb

> shrinkage(babel.db)

Thread 1 "R" hit Catchpoint 1 (exception thrown), 0x00007ffff4eae4a1 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff4eae4a1 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007fffecd260bb in Rcpp::internal::primitive_as<bool> (x=0x555555580cd0) at /usr/lib/R/site-library/Rcpp/include/Rcpp/as.h:34
#2  0x00007fffecd2585b in Rcpp::internal::as<bool> (x=0x555555580cd0) at /usr/lib/R/site-library/Rcpp/include/Rcpp/as.h:44
#3  0x00007fffecd24dbc in Rcpp::as<bool> (x=0x555555580cd0) at /usr/lib/R/site-library/Rcpp/include/Rcpp/as.h:152
#4  0x00007fffecd2386f in Rcpp::InputParameter<bool>::operator bool (this=0x7fffffff4060)
    at /usr/lib/R/site-library/Rcpp/include/Rcpp/InputParameter.h:34
#5  0x00007fffecd1bf06 in _babelmixr2_popedMultipleEndpointParam (pSEXP=0x555561070388, timesSEXP=0x555565d296b8,
    modelSwitchSEXP=0x555565d29958, maxMTSEXP=0x555560419460, optTimeSEXP=0x555555580cd0) at RcppExports.cpp:82

```

**Comment by mattfidler** [comment]
Thanks @TheoPapath 

This should be fixed (and tested so it doens't break again) in #132
