### ISSUE TITLE
poped - laplace in example ex.2.d.warfarin.ED.babelmixr2.R

### ISSUE THREAD

**Issue by TheoPapath** [nlmixr2/babelmixr2#138]
Laplace in line 90 was commented out, but it works well from my end. Not sure if this was fixed by another issue, but looks good now. Results match the poped examples too. 

Still receiving an error when parallelization is swathed on though (similar to issue #137)

**Comment by mattfidler** [comment]
Andy fixed this, 

Parallelization could be fixed on the next `PopED` release.
