### ISSUE TITLE
poped - ED optimization

### ISSUE THREAD

**Issue by TheoPapath** [nlmixr2/babelmixr2#140]
Looking at ex.3.b.PKPD.1.comp.oral.md.imax.ED-opt.babelmixr2.R
I believe we spoke about this, but ED optimization does not work right now, correct? 

![image](https://github.com/user-attachments/assets/81beddc2-d18d-4cda-b41d-c188d8a2f4a2)

The error I am receiving from my end looks very similar to the error in #137

**Comment by mattfidler** [comment]
This works just fine with the `babelmixr2`/`PopED` combination described in #137
