### ISSUE TITLE
Better zero protection for Yeo-Johnson?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/babelmixr2#21]
Should this line test for something sufficiently close to zero rather than equality to zero (e.g. `LAMBDA .GE. 0.0000001 .AND. LAMBDA .LE. 0.0000001`?

https://github.com/nlmixr2/babelmixr2/blob/d968e068055044060eb28db740bfebaba4064bb1/inst/err-yeoJohnson.txt#L3-L4

Similarly, should this protect for sufficiently close to 2 rather than equality?

https://github.com/nlmixr2/babelmixr2/blob/d968e068055044060eb28db740bfebaba4064bb1/inst/err-yeoJohnson.txt#L11-L12

**Comment by mattfidler** [comment]
In theory this only applies when they are exactly 2 or 1, but it could be fine protecting from zero.  Not sure what PsN does

**Comment by billdenney** [comment]
I see PsN (optionally) using Box-Cox but not Yeo-Johnson.  I'm not sure that this is an important fix, so I'll close this for now.

**Comment by mattfidler** [comment]
They do something for the zero case for cox-box, but if I recall it is only checking exactly zero.

**Comment by billdenney** [comment]
With a quick look, I don't see any zero-protection: https://github.com/UUPharmacometrics/PsN/blob/d7fb7222fd05a8440f0b116cee1c6fd1d68c5860/lib/model_transformations.pm#L702
