### ISSUE TITLE
How is genRxControl used?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/babelmixr2#24]
I'm trying to document `nonmemControl()`, but I'm not sure the purpose of the only allowed `...` argument of `genRxControl`.  Why isn't it inferred from the `rxControl` argument (or a simpler named argument)?

https://github.com/nlmixr2/babelmixr2/blob/d968e068055044060eb28db740bfebaba4064bb1/R/nonmemControl.R#L78-L81

**Comment by mattfidler** [comment]
This comes from `foceiControl` where there are hidden options that are set at run time.  The `foceiContol()` will validate the options and then make sure they are OK including allowing the hidden options.

This is true here too.  Here the `genRxControl` is an argument to see if the `rxControl` is at the default state I think.

**Comment by billdenney** [comment]
That makes sense.  Thanks.
