### ISSUE TITLE
Invalid `.cov` subscripts for Monolix

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/babelmixr2#27]
When running this test:

https://github.com/nlmixr2/babelmixr2/blob/5adebcf375d6ef6331940d2d6fe4d16d223c3af4/tests/testthat/test-monolix-read.R#L56-L63

I get this error:

```r
Error in .cov[.n, .n] : subscript out of bounds
Error: subscript out of bounds
```

It comes from here:

https://github.com/nlmixr2/babelmixr2/blob/5adebcf375d6ef6331940d2d6fe4d16d223c3af4/R/monolixReadData.R#L417-L420

The issue is that `.muRef` is `NULL` which comes from the fact that `x$getSplitMuModel` is `NULL` just above that.

I don't readily see where `x$getSplitMuModel` is supposed to come from.

**Comment by mattfidler** [comment]
It comes from the `.ui`
