### ISSUE TITLE
lixoftConnectors No Longer Available Online

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/babelmixr2#53]
It appears that the lixoftConnectors package has been removed from general availability, unless you have a Monolix installation:  https://monolix.lixoft.com/monolix-api/lixoftconnectors_installation/

I think that means that the `Additional_repositories` line should be removed from the DESCRIPTION, but I don't know what that will mean, in general, for the acceptance of this as a package.

**Comment by mattfidler** [comment]
I don't think it was ever available online.  To me this still falls in the CRAN policy.  The `Additional_repositories` are for packages that are available in a CRAN-like repository.

Here is the CRAN policy that relates to this

> Packages on which a CRAN package depends should be available from a mainstream repository: if any mentioned in ‘Suggests’ or ‘Enhances’ fields are not from such a repository, where to obtain them at a repository should be specified in an ‘Additional_repositories’ field of the DESCRIPTION file (as a comma-separated list of repository URLs) or for other means of access, described in the ‘Description’ field.
> A package listed in ‘Suggests’ or ‘Enhances’ should be used conditionally in examples or tests if it cannot straightforwardly be installed on the major R platforms. (‘Writing R Extensions’ recommends that they are always used conditionally.)
> Orphaned CRAN packages should not be strict requirements (in the ‘Depends’, ‘Imports’ or ‘LinkingTo’ fields, including indirectly). They are allowed in ‘Suggests’ if used conditionally, although this is discouraged.

The corresponding line is *or for other means of access, described in the ‘Description’ field.*

This is what I determined with `ggPMX` and CRAN accepted it without any complaint.

**Comment by mattfidler** [comment]
Worst case scenario provide an example of how to use a function to run the `lixoftConnectors`
