### ISSUE TITLE
Invalid NONMEM XML file causes error

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/babelmixr2#60]
In a recent test run, NONMEM completed the run successfully, but the xml file was truncated.  In this case, should we try another method to load one of the other output files?

Should this be fixed here or in `pmxTools`?

**Comment by mattfidler** [comment]
Probably pmxTools.  Or here if we want to use a non xml method.  @kestrel99 mentioned a non xml method that @RikSchoemaker  uses

**Comment by billdenney** [comment]
As I've looked more, it's not an easily-fixable issue either place.  The XML file appears to be missing not just some of the closing tags but also some of the needed data.  Having it throw an error is likely the best path.  We may want to make the error clearer, but otherwise, I think we can leave it for now.

**Comment by kestrel99** [comment]
I'll fix it when I get back. In the meantime can you flag it on the pmxTools GitHub page so I don't forget?

**Comment by mattfidler** [comment]
xml reader is used to calculate
- nonmem run time
- nmtran message
- termination message
- covariance information

**Comment by mattfidler** [comment]
The lst reader gives
- termination message
- ofv

**Comment by billdenney** [comment]
Covariance comes pretty easily from reading the .cov file.  I don't know if run time comes easily from another source (though I also don't think it seems to be required...).

**Comment by mattfidler** [comment]
I am writing a `.lst` parser right now (since most of the ddmore files don't contain `.ext` files), I can get the run time from that parser.  I looked at `pmxTools` `.lst` parser and it doesn't get as much as I thought it did.

**Comment by billdenney** [comment]
PsN has a .lst parser that covers a lot of the potential issues that come up in edge cases.  You may want to look at it while you're at it.

**Comment by billdenney** [comment]
Also, I think that the .cov file has more precision than the .lst file for the covariance matrix (i.e. more significant figures).

**Comment by mattfidler** [comment]
After thinking a bit, all I will extract is the parameter estimates for now.  `lst` parsing is a pain.

**Comment by mattfidler** [comment]
https://github.com/UUPharmacometrics/PsN/blob/18f6d39677506ab568134cf3965c6af7bbda6b99/lib/output/problem/subproblem.pm

if you are looking

**Comment by billdenney** [comment]
That's about what I remembered.

**Comment by mattfidler** [comment]
Write the parser in `nonmem2rx`
