### ISSUE TITLE
genRxControl is NULL for `pkncaControl()`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/babelmixr2#75]
@mattfidler, When I'm using `pkncaControl()`, the `genRxControl` item is not present.  That causes an error at this line:

https://github.com/nlmixr2/nlmixr2est/blob/7204214a9aaa324ad5ac04055d88fda2ea49f02e/R/nlmixr2.R#L253

Should I set it to `FALSE` within `pkncaControl()` or does it make more sense to modify that line to check for `NULL`?  Maybe make that line into `isTRUE(.ctl$genRxControl)`?

**Comment by billdenney** [comment]
I'm not sure why it works some times and not others.  It may be package load order.

**Comment by mattfidler** [comment]
Its seeing if it can adjust parameters.  Sometimes it can sometimes it cant.  I suppose isTRUE makes more sense
